function [labelNum,hemisphere,lobe,gyrus,tissuetype,celltype]=loadTalLabels(labelFilePath)
% 
% loadTalLabels
% -------------------------------------------------------------------------
% usage: load talairach label data 
% 
% INPUT:
%   labelFilePath - path to talairach label file
% 
% OUTPUT:
%   labelnum - label numbers 
%   hemisphere, lobe, etc. - string arrays giving the labels that
%   correspond to each labelNum
% 
% 
% author: Kelly, kelhennigan@gmail.com, 26-Mar-2015

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Script for importing data from the following text file:
%
%    /Users/Kelly/Documents/Brain_Atlases/talairach_nii_labels/labels.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/03/26 16:14:07

%% Initialize variables.

if notDefined('labelFilePath')
 labelFilePath = '/Users/Kelly/Documents/Brain_Atlases/talairach_nii_labels/labels.txt';
end

delimiter = {'\t','.'};
formatSpec = '%f%s%s%s%s%s%[^\n\r]';


%% Open the text file.
fileID = fopen(labelFilePath,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);


%% Allocate imported array to column variable names
labelNum = dataArray{:, 1};
hemisphere = dataArray{:, 2};
lobe = dataArray{:, 3};
gyrus = dataArray{:, 4};
tissuetype = dataArray{:, 5};
celltype = dataArray{:, 6};

